### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by pmargreff** [motherknows/aws_ssm_provider#14]
How secrets are resolved? Can you add some usage section please?

**Comment by erikosmond** [comment]
@pmargreff Thanks for your interest in aws_ssm_provider. Please read our related blog post and let us know if you have any further, or maybe more specific, usage questions. https://dev.to/caredox/secrets-management-in-elixir-using-aws-4d9b

**Comment by luke-bravenboer** [comment]
Seconded - to be more specific, how do you actually use the secrets in your Elixir code?

The linked blog post only contains information on how to configure this plugin to read from a file on the local filesystem, no actual usage instructions.

The README.md seems to imply that it's loading everything into elixir's application config, but doesn't specifically say for certain - and I can't figure out the right parameters to send to Application.fetch_env to get secrets back out again, so I feel like I'm misunderstanding something.
